name: Trigger auto deployment for superset

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/superset-AutoDeployTrigger-dfb9ffba-d757-4a67-bd28-9e51ac390625.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.SUPERSET_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.SUPERSET_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.SUPERSET_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: 
          registryUsername: ${{ secrets.SUPERSET_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.SUPERSET_REGISTRY_PASSWORD }}
          containerAppName: superset
          resourceGroup: Superset
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


